// Generated from the application's prepared statements. Never accept arbitrary SQL.
export const storageQueries: string[] = [
  "DELETE FROM admin_sessions WHERE expires_at<=? OR id=?",
  "DELETE FROM admin_sessions WHERE id=?",
  "DELETE FROM products WHERE id=?",
  "DELETE FROM rate_limits WHERE id=?",
  "INSERT INTO admin_sessions(id,username,credential_version,expires_at) VALUES(?,?,?,?)",
  "INSERT INTO carts(id,data,updated_at) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at",
  "INSERT INTO categories(id,name,data) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,data=excluded.data",
  "INSERT INTO messages(id,data,created_at) VALUES(?,?,?)",
  "INSERT INTO products(id,slug,status,stock,created_at,data) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,status=excluded.status,stock=excluded.stock,data=excluded.data",
  "INSERT INTO rate_limits(id,count,expires) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=CASE WHEN expires<=? THEN 1 ELSE count+1 END, expires=CASE WHEN expires<=? THEN excluded.expires ELSE expires END RETURNING count",
  "INSERT INTO rate_limits(id,count,expires) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count",
  "INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",
  "INSERT INTO uploads(id,name,created_at) VALUES(?,?,?)",
  "INSERT INTO users(id,email,role) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email",
  "INSERT OR IGNORE INTO categories(id,name,data) VALUES(?,?,?)",
  "INSERT OR IGNORE INTO products(id,slug,status,stock,created_at,data) VALUES(?,?,?,?,?,?)",
  "INSERT OR IGNORE INTO settings(key,value) VALUES(?,?)",
  "SELECT * FROM uploads ORDER BY created_at DESC LIMIT 500",
  "SELECT data FROM carts WHERE id=?",
  "SELECT data FROM categories ORDER BY name",
  "SELECT data FROM products ORDER BY created_at DESC",
  "SELECT id FROM products WHERE slug=? AND id<>?",
  "SELECT id,data,created_at FROM messages ORDER BY created_at DESC LIMIT 100",
  "SELECT username,credential_version FROM admin_sessions WHERE id=? AND expires_at>?",
  "SELECT value FROM settings WHERE key = ?",
  "SELECT value FROM settings WHERE key=?"
];
